
// This file has been generated by the GUI designer. Do not modify.
namespace Yamster
{
	public partial class ConversationsScreen
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Button btnCancelSearch;
		
		private global::Gtk.Image ctlSearchImage;
		
		private global::Gtk.Entry txtSearch;
		
		private global::Gtk.Label label1;
		
		private global::Yamster.Grid ctlGrid;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.CheckButton chkShowMultiParticipant;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Yamster.ConversationsScreen
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Yamster.ConversationsScreen";
			// Container child Yamster.ConversationsScreen.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(6));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox2.Add (this.fixed1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed1]));
			w1.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnCancelSearch = new global::Gtk.Button ();
			this.btnCancelSearch.CanFocus = true;
			this.btnCancelSearch.Name = "btnCancelSearch";
			this.btnCancelSearch.Label = global::Mono.Unix.Catalog.GetString ("X");
			this.hbox2.Add (this.btnCancelSearch);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnCancelSearch]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ctlSearchImage = new global::Gtk.Image ();
			this.ctlSearchImage.Name = "ctlSearchImage";
			this.ctlSearchImage.Xalign = 0F;
			this.ctlSearchImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Yamster.Resources.Search.png");
			this.hbox2.Add (this.ctlSearchImage);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ctlSearchImage]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.txtSearch = new global::Gtk.Entry ();
			this.txtSearch.WidthRequest = 250;
			this.txtSearch.CanFocus = true;
			this.txtSearch.Name = "txtSearch";
			this.txtSearch.IsEditable = true;
			this.txtSearch.InvisibleChar = '●';
			this.hbox2.Add (this.txtSearch);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtSearch]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 3;
			w4.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Find Person:");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.ctlGrid = new global::Yamster.Grid ();
			this.ctlGrid.Events = ((global::Gdk.EventMask)(256));
			this.ctlGrid.Name = "ctlGrid";
			this.vbox1.Add (this.ctlGrid);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.ctlGrid]));
			w7.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.chkShowMultiParticipant = new global::Gtk.CheckButton ();
			this.chkShowMultiParticipant.CanFocus = true;
			this.chkShowMultiParticipant.Name = "chkShowMultiParticipant";
			this.chkShowMultiParticipant.Label = global::Mono.Unix.Catalog.GetString ("Show conversations with multiple participants");
			this.chkShowMultiParticipant.DrawIndicator = true;
			this.chkShowMultiParticipant.UseUnderline = true;
			this.chkShowMultiParticipant.Xalign = 1F;
			this.hbox1.Add (this.chkShowMultiParticipant);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.chkShowMultiParticipant]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 1;
			w8.Expand = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.btnCancelSearch.Hide ();
			this.ctlSearchImage.Hide ();
			this.Hide ();
			this.txtSearch.Changed += new global::System.EventHandler (this.txtSearch_Changed);
			this.btnCancelSearch.Clicked += new global::System.EventHandler (this.btnCancelSearch_Clicked);
			this.ctlGrid.FocusedItemChanged += new global::System.EventHandler (this.ctlGrid_FocusedItemChanged);
			this.chkShowMultiParticipant.Clicked += new global::System.EventHandler (this.chkShowMultiParticipant_Clicked);
		}
	}
}
