
// This file has been generated by the GUI designer. Do not modify.
namespace Yamster
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action mnuFile;
		
		private global::Gtk.Action mnuHelp;
		
		private global::Gtk.Action mnuHelpAbout;
		
		private global::Gtk.Action mnuFileExit;
		
		private global::Gtk.Action mnuYammerSyncAction;
		
		private global::Gtk.Action OnlineDocumentationAction;
		
		private global::Gtk.Action mnuHelpWebSite;
		
		private global::Gtk.Action mnuHelpDiscussionGroup;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar ctlMenuBar;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Notebook ctlScreenBox;
		
		private global::Yamster.ViewsScreen ctlViewsScreen;
		
		private global::Gtk.Label label4;
		
		private global::Yamster.GroupThreadScreen ctlGroupThreadScreen;
		
		private global::Gtk.Label label7;
		
		private global::Yamster.ConversationsScreen ctlConversationsScreen;
		
		private global::Gtk.Label label9;
		
		private global::Yamster.SearchScreen ctlSearchScreen;
		
		private global::Gtk.Label lblScreenSearch;
		
		private global::Yamster.GroupConfigScreen ctlGroupConfigScreen;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.VBox vbox10;
		
		private global::Gtk.HBox hbox11;
		
		private global::Gtk.Button btnAboutBox;
		
		private global::Gtk.Button btnSync;
		
		private global::Gtk.Button btnTest;
		
		private global::Yamster.ThreadViewer ctlThreadViewer;
		
		private global::Gtk.HBox ctlStatusBarHbox;
		
		private global::Gtk.Statusbar ctlStatusBarMain;
		
		private global::Gtk.Statusbar ctlStatusBarTotalYams;
		
		private global::Gtk.Statusbar ctlStatusBarSyncStatus;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Yamster.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.mnuFile = new global::Gtk.Action ("mnuFile", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
			this.mnuFile.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
			w1.Add (this.mnuFile, null);
			this.mnuHelp = new global::Gtk.Action ("mnuHelp", global::Mono.Unix.Catalog.GetString ("_Help"), null, null);
			this.mnuHelp.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
			w1.Add (this.mnuHelp, null);
			this.mnuHelpAbout = new global::Gtk.Action ("mnuHelpAbout", global::Mono.Unix.Catalog.GetString ("_About Yamster..."), null, null);
			this.mnuHelpAbout.ShortLabel = global::Mono.Unix.Catalog.GetString ("_About Yamster...");
			w1.Add (this.mnuHelpAbout, null);
			this.mnuFileExit = new global::Gtk.Action ("mnuFileExit", global::Mono.Unix.Catalog.GetString ("E_xit"), null, null);
			this.mnuFileExit.ShortLabel = global::Mono.Unix.Catalog.GetString ("E_xit");
			w1.Add (this.mnuFileExit, null);
			this.mnuYammerSyncAction = new global::Gtk.Action ("mnuYammerSyncAction", global::Mono.Unix.Catalog.GetString ("_Yammer Sync..."), null, null);
			this.mnuYammerSyncAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Yammer Sync...");
			w1.Add (this.mnuYammerSyncAction, null);
			this.OnlineDocumentationAction = new global::Gtk.Action ("OnlineDocumentationAction", global::Mono.Unix.Catalog.GetString ("Online _Documentation..."), null, null);
			this.OnlineDocumentationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Online _Documentation...");
			w1.Add (this.OnlineDocumentationAction, "F1");
			this.mnuHelpWebSite = new global::Gtk.Action ("mnuHelpWebSite", global::Mono.Unix.Catalog.GetString ("_Yamster Web Site"), null, null);
			this.mnuHelpWebSite.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Yamster Web Site");
			w1.Add (this.mnuHelpWebSite, null);
			this.mnuHelpDiscussionGroup = new global::Gtk.Action ("mnuHelpDiscussionGroup", global::Mono.Unix.Catalog.GetString ("_Ask a Question..."), null, null);
			this.mnuHelpDiscussionGroup.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Ask a Question...");
			w1.Add (this.mnuHelpDiscussionGroup, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Yamster.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Yamster!");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Yamster.Resources.Yamster-16x16.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Yamster.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><menubar name='ctlMenuBar'><menu name='mnuFile' action='mnuFile'><menuitem name='mnuYammerSyncAction' action='mnuYammerSyncAction'/><separator/><menuitem name='mnuFileExit' action='mnuFileExit'/></menu><menu name='mnuHelp' action='mnuHelp'><menuitem name='OnlineDocumentationAction' action='OnlineDocumentationAction'/><menuitem name='mnuHelpDiscussionGroup' action='mnuHelpDiscussionGroup'/><menuitem name='mnuHelpWebSite' action='mnuHelpWebSite'/><separator/><menuitem name='mnuHelpAbout' action='mnuHelpAbout'/></menu></menubar></ui>");
			this.ctlMenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/ctlMenuBar")));
			this.ctlMenuBar.Name = "ctlMenuBar";
			this.vbox1.Add (this.ctlMenuBar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.ctlMenuBar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			this.hbox2.BorderWidth = ((uint)(5));
			// Container child hbox2.Gtk.Box+BoxChild
			this.ctlScreenBox = new global::Gtk.Notebook ();
			this.ctlScreenBox.CanFocus = true;
			this.ctlScreenBox.Name = "ctlScreenBox";
			this.ctlScreenBox.CurrentPage = 0;
			// Container child ctlScreenBox.Gtk.Notebook+NotebookChild
			this.ctlViewsScreen = new global::Yamster.ViewsScreen ();
			this.ctlViewsScreen.Events = ((global::Gdk.EventMask)(256));
			this.ctlViewsScreen.Name = "ctlViewsScreen";
			this.ctlScreenBox.Add (this.ctlViewsScreen);
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("_Views");
			this.label4.UseUnderline = true;
			this.ctlScreenBox.SetTabLabel (this.ctlViewsScreen, this.label4);
			this.label4.ShowAll ();
			// Container child ctlScreenBox.Gtk.Notebook+NotebookChild
			this.ctlGroupThreadScreen = new global::Yamster.GroupThreadScreen ();
			this.ctlGroupThreadScreen.Events = ((global::Gdk.EventMask)(256));
			this.ctlGroupThreadScreen.Name = "ctlGroupThreadScreen";
			this.ctlScreenBox.Add (this.ctlGroupThreadScreen);
			global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.ctlScreenBox [this.ctlGroupThreadScreen]));
			w4.Position = 1;
			// Notebook tab
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("_Groups");
			this.label7.UseUnderline = true;
			this.ctlScreenBox.SetTabLabel (this.ctlGroupThreadScreen, this.label7);
			this.label7.ShowAll ();
			// Container child ctlScreenBox.Gtk.Notebook+NotebookChild
			this.ctlConversationsScreen = new global::Yamster.ConversationsScreen ();
			this.ctlConversationsScreen.Events = ((global::Gdk.EventMask)(256));
			this.ctlConversationsScreen.Name = "ctlConversationsScreen";
			this.ctlScreenBox.Add (this.ctlConversationsScreen);
			global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.ctlScreenBox [this.ctlConversationsScreen]));
			w5.Position = 2;
			// Notebook tab
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("_Conversations");
			this.label9.UseUnderline = true;
			this.ctlScreenBox.SetTabLabel (this.ctlConversationsScreen, this.label9);
			this.label9.ShowAll ();
			// Container child ctlScreenBox.Gtk.Notebook+NotebookChild
			this.ctlSearchScreen = new global::Yamster.SearchScreen ();
			this.ctlSearchScreen.Events = ((global::Gdk.EventMask)(256));
			this.ctlSearchScreen.Name = "ctlSearchScreen";
			this.ctlScreenBox.Add (this.ctlSearchScreen);
			global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.ctlScreenBox [this.ctlSearchScreen]));
			w6.Position = 3;
			// Notebook tab
			this.lblScreenSearch = new global::Gtk.Label ();
			this.lblScreenSearch.Name = "lblScreenSearch";
			this.lblScreenSearch.LabelProp = global::Mono.Unix.Catalog.GetString ("_Search");
			this.lblScreenSearch.UseUnderline = true;
			this.ctlScreenBox.SetTabLabel (this.ctlSearchScreen, this.lblScreenSearch);
			this.lblScreenSearch.ShowAll ();
			// Container child ctlScreenBox.Gtk.Notebook+NotebookChild
			this.ctlGroupConfigScreen = new global::Yamster.GroupConfigScreen ();
			this.ctlGroupConfigScreen.Events = ((global::Gdk.EventMask)(256));
			this.ctlGroupConfigScreen.Name = "ctlGroupConfigScreen";
			this.ctlScreenBox.Add (this.ctlGroupConfigScreen);
			global::Gtk.Notebook.NotebookChild w7 = ((global::Gtk.Notebook.NotebookChild)(this.ctlScreenBox [this.ctlGroupConfigScreen]));
			w7.Position = 4;
			// Notebook tab
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Sync Settings");
			this.label17.UseUnderline = true;
			this.ctlScreenBox.SetTabLabel (this.ctlGroupConfigScreen, this.label17);
			this.label17.ShowAll ();
			this.hbox2.Add (this.ctlScreenBox);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ctlScreenBox]));
			w8.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.WidthRequest = 380;
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			this.vbox10.BorderWidth = ((uint)(5));
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.btnAboutBox = new global::Gtk.Button ();
			this.btnAboutBox.CanFocus = true;
			this.btnAboutBox.Name = "btnAboutBox";
			this.btnAboutBox.UseUnderline = true;
			this.btnAboutBox.Label = global::Mono.Unix.Catalog.GetString ("_About Yamster...");
			this.hbox11.Add (this.btnAboutBox);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.btnAboutBox]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.btnSync = new global::Gtk.Button ();
			this.btnSync.CanFocus = true;
			this.btnSync.Name = "btnSync";
			this.btnSync.UseUnderline = true;
			this.btnSync.Label = global::Mono.Unix.Catalog.GetString ("_Yammer Sync...");
			this.hbox11.Add (this.btnSync);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.btnSync]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.btnTest = new global::Gtk.Button ();
			this.btnTest.CanFocus = true;
			this.btnTest.Name = "btnTest";
			this.btnTest.UseUnderline = true;
			this.btnTest.Label = global::Mono.Unix.Catalog.GetString ("Test");
			this.hbox11.Add (this.btnTest);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.btnTest]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox10.Add (this.hbox11);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox11]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.ctlThreadViewer = new global::Yamster.ThreadViewer ();
			this.ctlThreadViewer.WidthRequest = 400;
			this.ctlThreadViewer.Events = ((global::Gdk.EventMask)(256));
			this.ctlThreadViewer.Name = "ctlThreadViewer";
			this.vbox10.Add (this.ctlThreadViewer);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.ctlThreadViewer]));
			w13.Position = 1;
			this.hbox2.Add (this.vbox10);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox10]));
			w14.Position = 1;
			w14.Expand = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w15.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.ctlStatusBarHbox = new global::Gtk.HBox ();
			this.ctlStatusBarHbox.Name = "ctlStatusBarHbox";
			this.ctlStatusBarHbox.Spacing = 6;
			// Container child ctlStatusBarHbox.Gtk.Box+BoxChild
			this.ctlStatusBarMain = new global::Gtk.Statusbar ();
			this.ctlStatusBarMain.Name = "ctlStatusBarMain";
			this.ctlStatusBarMain.Spacing = 6;
			this.ctlStatusBarMain.HasResizeGrip = false;
			this.ctlStatusBarHbox.Add (this.ctlStatusBarMain);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.ctlStatusBarHbox [this.ctlStatusBarMain]));
			w16.Position = 0;
			// Container child ctlStatusBarHbox.Gtk.Box+BoxChild
			this.ctlStatusBarTotalYams = new global::Gtk.Statusbar ();
			this.ctlStatusBarTotalYams.WidthRequest = 150;
			this.ctlStatusBarTotalYams.Name = "ctlStatusBarTotalYams";
			this.ctlStatusBarTotalYams.Spacing = 6;
			this.ctlStatusBarTotalYams.HasResizeGrip = false;
			this.ctlStatusBarHbox.Add (this.ctlStatusBarTotalYams);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.ctlStatusBarHbox [this.ctlStatusBarTotalYams]));
			w17.Position = 1;
			w17.Expand = false;
			// Container child ctlStatusBarHbox.Gtk.Box+BoxChild
			this.ctlStatusBarSyncStatus = new global::Gtk.Statusbar ();
			this.ctlStatusBarSyncStatus.WidthRequest = 100;
			this.ctlStatusBarSyncStatus.Name = "ctlStatusBarSyncStatus";
			this.ctlStatusBarSyncStatus.Spacing = 6;
			this.ctlStatusBarHbox.Add (this.ctlStatusBarSyncStatus);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.ctlStatusBarHbox [this.ctlStatusBarSyncStatus]));
			w18.Position = 2;
			w18.Expand = false;
			this.vbox1.Add (this.ctlStatusBarHbox);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.ctlStatusBarHbox]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 985;
			this.DefaultHeight = 649;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.mnuHelpAbout.Activated += new global::System.EventHandler (this.mnuHelpAbout_Activated);
			this.mnuFileExit.Activated += new global::System.EventHandler (this.mnuFileExit_Activated);
			this.mnuYammerSyncAction.Activated += new global::System.EventHandler (this.mnuFileYammerSync_Activated);
			this.OnlineDocumentationAction.Activated += new global::System.EventHandler (this.mnuHelpManual_Activated);
			this.mnuHelpWebSite.Activated += new global::System.EventHandler (this.mnuHelpWebSite_Activated);
			this.mnuHelpDiscussionGroup.Activated += new global::System.EventHandler (this.mnuHelpDiscussionGroup_Activated);
			this.btnTest.Clicked += new global::System.EventHandler (this.btnTest_Click);
			this.btnSync.Clicked += new global::System.EventHandler (this.btnSync_Click);
			this.btnAboutBox.Clicked += new global::System.EventHandler (this.btnAboutBox_Clicked);
		}
	}
}
