
// This file has been generated by the GUI designer. Do not modify.
namespace Yamster
{
	public partial class AboutWindow
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.EventBox ctlLeftBox;
		
		private global::Gtk.Image image1;
		
		private global::Gtk.EventBox ctlRightBox;
		
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Image image2;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label lblBuildNumber;
		
		private global::Gtk.Label lblBuildNumber1;
		
		private global::Gtk.Label lblLicense;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Label lblHelpManual;
		
		private global::Gtk.Label lblDiscussionGroup;
		
		private global::Gtk.Label lblWebSite;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Yamster.AboutWindow
			this.WidthRequest = 360;
			this.HeightRequest = 215;
			this.Name = "Yamster.AboutWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("About Yamster");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Yamster.Resources.Yamster-16x16.png");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 360;
			this.DefaultHeight = 215;
			this.Decorated = false;
			// Container child Yamster.AboutWindow.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			// Container child hbox1.Gtk.Box+BoxChild
			this.ctlLeftBox = new global::Gtk.EventBox ();
			this.ctlLeftBox.Name = "ctlLeftBox";
			// Container child ctlLeftBox.Gtk.Container+ContainerChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Xalign = 0F;
			this.image1.Yalign = 0F;
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Yamster.Resources.AboutBoxLeft.png");
			this.ctlLeftBox.Add (this.image1);
			this.hbox1.Add (this.ctlLeftBox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ctlLeftBox]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ctlRightBox = new global::Gtk.EventBox ();
			this.ctlRightBox.Name = "ctlRightBox";
			// Container child ctlRightBox.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(10));
			this.alignment1.RightPadding = ((uint)(16));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Xalign = 0F;
			this.image2.Yalign = 0F;
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Yamster.Resources.AboutBoxTop.png");
			this.vbox1.Add (this.image2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.image2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblBuildNumber = new global::Gtk.Label ();
			this.lblBuildNumber.Name = "lblBuildNumber";
			this.lblBuildNumber.Xalign = 0F;
			this.lblBuildNumber.Yalign = 0F;
			this.lblBuildNumber.LabelProp = global::Mono.Unix.Catalog.GetString ("Build X.X.X");
			this.vbox2.Add (this.lblBuildNumber);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblBuildNumber]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblBuildNumber1 = new global::Gtk.Label ();
			this.lblBuildNumber1.Name = "lblBuildNumber1";
			this.lblBuildNumber1.Xalign = 0F;
			this.lblBuildNumber1.Yalign = 0F;
			this.lblBuildNumber1.LabelProp = global::Mono.Unix.Catalog.GetString ("Copyright (c) Microsoft Corporation");
			this.vbox2.Add (this.lblBuildNumber1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblBuildNumber1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblLicense = new global::Gtk.Label ();
			this.lblLicense.Name = "lblLicense";
			this.lblLicense.Xalign = 0F;
			this.lblLicense.Yalign = 0F;
			this.lblLicense.LabelProp = global::Mono.Unix.Catalog.GetString ("Released under the <a href=\"\">The MIT License</a>");
			this.lblLicense.UseMarkup = true;
			this.vbox2.Add (this.lblLicense);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblLicense]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.HeightRequest = 5;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox2.Add (this.fixed1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.fixed1]));
			w7.Position = 3;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblHelpManual = new global::Gtk.Label ();
			this.lblHelpManual.Name = "lblHelpManual";
			this.lblHelpManual.Xalign = 0F;
			this.lblHelpManual.Yalign = 0F;
			this.lblHelpManual.LabelProp = global::Mono.Unix.Catalog.GetString ("<a href=\"\">Online Documentation</a>");
			this.lblHelpManual.UseMarkup = true;
			this.vbox2.Add (this.lblHelpManual);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblHelpManual]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblDiscussionGroup = new global::Gtk.Label ();
			this.lblDiscussionGroup.Name = "lblDiscussionGroup";
			this.lblDiscussionGroup.Xalign = 0F;
			this.lblDiscussionGroup.Yalign = 0F;
			this.lblDiscussionGroup.LabelProp = global::Mono.Unix.Catalog.GetString ("<a href=\"\">Ask a Question...</a>");
			this.lblDiscussionGroup.UseMarkup = true;
			this.vbox2.Add (this.lblDiscussionGroup);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblDiscussionGroup]));
			w9.Position = 5;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblWebSite = new global::Gtk.Label ();
			this.lblWebSite.Name = "lblWebSite";
			this.lblWebSite.Xalign = 0F;
			this.lblWebSite.Yalign = 0F;
			this.lblWebSite.LabelProp = global::Mono.Unix.Catalog.GetString ("<a href=\"\">Yamster Web Site</a>");
			this.lblWebSite.UseMarkup = true;
			this.vbox2.Add (this.lblWebSite);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblWebSite]));
			w10.Position = 6;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.alignment1.Add (this.vbox1);
			this.ctlRightBox.Add (this.alignment1);
			this.hbox1.Add (this.ctlRightBox);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ctlRightBox]));
			w14.Position = 1;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.Window_KeyPress);
			this.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.Window_ButtonRelease);
			this.lblLicense.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.lblLicense_ButtonPress);
			this.lblHelpManual.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.lblHelpManual_ButtonPress);
			this.lblDiscussionGroup.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.lblDiscussionGroup_ButtonPress);
			this.lblWebSite.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.lblWebSite_ButtonPress);
		}
	}
}
