
// This file has been generated by the GUI designer. Do not modify.
namespace Yamster
{
	public partial class ThreadViewerDivider
	{
		private global::Gtk.EventBox ctlOuterBox;
		
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.EventBox ctlColorBox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Yamster.ThreadViewerDivider
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Yamster.ThreadViewerDivider";
			// Container child Yamster.ThreadViewerDivider.Gtk.Container+ContainerChild
			this.ctlOuterBox = new global::Gtk.EventBox ();
			this.ctlOuterBox.Name = "ctlOuterBox";
			// Container child ctlOuterBox.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(3));
			this.alignment1.TopPadding = ((uint)(12));
			this.alignment1.RightPadding = ((uint)(8));
			this.alignment1.BottomPadding = ((uint)(6));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.ctlColorBox = new global::Gtk.EventBox ();
			this.ctlColorBox.HeightRequest = 10;
			this.ctlColorBox.Name = "ctlColorBox";
			this.alignment1.Add (this.ctlColorBox);
			this.ctlOuterBox.Add (this.alignment1);
			this.Add (this.ctlOuterBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
