
// This file has been generated by the GUI designer. Do not modify.
namespace Yamster
{
	public partial class MessageGrid
	{
		private global::Yamster.Grid ctlGrid;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Yamster.MessageGrid
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Yamster.MessageGrid";
			// Container child Yamster.MessageGrid.Gtk.Container+ContainerChild
			this.ctlGrid = new global::Yamster.Grid ();
			this.ctlGrid.Events = ((global::Gdk.EventMask)(256));
			this.ctlGrid.Name = "ctlGrid";
			this.Add (this.ctlGrid);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
