
// This file has been generated by the GUI designer. Do not modify.
namespace Yamster
{
	public partial class ViewsScreen
	{
		private global::Gtk.HPaned hpaned1;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label label1;
		
		private global::Yamster.Grid ctlQueriesGrid;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Notebook ctlNotebook;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label label2;
		
		private global::Yamster.ThreadGrid ctlThreadGrid;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.CheckButton chkShowReadThreads;
		
		private global::Gtk.Label lblMarkAllRead;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label label6;
		
		private global::Yamster.MessageGrid ctlMessageGrid;
		
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Label label4;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Yamster.ViewsScreen
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Yamster.ViewsScreen";
			// Container child Yamster.ViewsScreen.Gtk.Container+ContainerChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 141;
			this.hpaned1.BorderWidth = ((uint)(6));
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Views");
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.ctlQueriesGrid = new global::Yamster.Grid ();
			this.ctlQueriesGrid.Events = ((global::Gdk.EventMask)(256));
			this.ctlQueriesGrid.Name = "ctlQueriesGrid";
			this.vbox1.Add (this.ctlQueriesGrid);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.ctlQueriesGrid]));
			w2.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.HeightRequest = 21;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed1]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.hpaned1.Add (this.vbox1);
			global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vbox1]));
			w4.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.ctlNotebook = new global::Gtk.Notebook ();
			this.ctlNotebook.CanFocus = true;
			this.ctlNotebook.Name = "ctlNotebook";
			this.ctlNotebook.CurrentPage = 1;
			this.ctlNotebook.ShowBorder = false;
			// Container child ctlNotebook.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Threads");
			this.vbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.ctlThreadGrid = new global::Yamster.ThreadGrid ();
			this.ctlThreadGrid.Events = ((global::Gdk.EventMask)(256));
			this.ctlThreadGrid.Name = "ctlThreadGrid";
			this.ctlThreadGrid.TrackRead = false;
			this.vbox2.Add (this.ctlThreadGrid);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.ctlThreadGrid]));
			w6.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.chkShowReadThreads = new global::Gtk.CheckButton ();
			this.chkShowReadThreads.CanFocus = true;
			this.chkShowReadThreads.Name = "chkShowReadThreads";
			this.chkShowReadThreads.Label = global::Mono.Unix.Catalog.GetString ("Show read threads");
			this.chkShowReadThreads.DrawIndicator = true;
			this.chkShowReadThreads.UseUnderline = true;
			this.hbox1.Add (this.chkShowReadThreads);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.chkShowReadThreads]));
			w7.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblMarkAllRead = new global::Gtk.Label ();
			this.lblMarkAllRead.Name = "lblMarkAllRead";
			this.lblMarkAllRead.Xalign = 1F;
			this.lblMarkAllRead.LabelProp = global::Mono.Unix.Catalog.GetString ("<a href=\"\">Mark All Read</a>");
			this.lblMarkAllRead.UseMarkup = true;
			this.hbox1.Add (this.lblMarkAllRead);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblMarkAllRead]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.ctlNotebook.Add (this.vbox2);
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
			this.ctlNotebook.SetTabLabel (this.vbox2, this.label5);
			this.label5.ShowAll ();
			// Container child ctlNotebook.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			// Container child vbox3.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Yams");
			this.vbox3.Add (this.label6);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label6]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.ctlMessageGrid = new global::Yamster.MessageGrid ();
			this.ctlMessageGrid.Events = ((global::Gdk.EventMask)(256));
			this.ctlMessageGrid.Name = "ctlMessageGrid";
			this.vbox3.Add (this.ctlMessageGrid);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.ctlMessageGrid]));
			w12.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.HeightRequest = 21;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.vbox3.Add (this.fixed2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed2]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.ctlNotebook.Add (this.vbox3);
			global::Gtk.Notebook.NotebookChild w14 = ((global::Gtk.Notebook.NotebookChild)(this.ctlNotebook [this.vbox3]));
			w14.Position = 1;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
			this.ctlNotebook.SetTabLabel (this.vbox3, this.label4);
			this.label4.ShowAll ();
			this.hpaned1.Add (this.ctlNotebook);
			this.Add (this.hpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.ctlQueriesGrid.FocusedItemChanged += new global::System.EventHandler (this.ctlQueriesGrid_FocusedItemChanged);
			this.ctlThreadGrid.FocusedItemChanged += new global::System.EventHandler (this.ctlThreadGrid_FocusedItemChanged);
			this.chkShowReadThreads.Toggled += new global::System.EventHandler (this.chkShowReadThreads_Toggled);
			this.lblMarkAllRead.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.lblMarkAllRead_ButtonPress);
			this.ctlMessageGrid.FocusedItemChanged += new global::System.EventHandler (this.ctlMessageGrid_FocusedItemChanged);
		}
	}
}
