
// This file has been generated by the GUI designer. Do not modify.
namespace Yamster
{
	public partial class SearchScreen
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Button btnSearch;
		
		private global::Gtk.Button btnShowYql;
		
		private global::Yamster.UserEntryWidget ctlLikedByUserEntry;
		
		private global::Yamster.UserEntryWidget ctlMentioningUserEntry;
		
		private global::Yamster.UserEntryWidget ctlSentByUserEntry;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.CheckButton chkWholeWords;
		
		private global::Gtk.RadioButton rbMatchAll;
		
		private global::Gtk.RadioButton rbMatchAny;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Entry txtSearch;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Yamster.MessageGrid ctlMessageViewer;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label lblSearchResults;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Yamster.SearchScreen
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Yamster.SearchScreen";
			// Container child Yamster.SearchScreen.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(6));
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(4)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.btnSearch = new global::Gtk.Button ();
			this.btnSearch.CanFocus = true;
			this.btnSearch.Name = "btnSearch";
			this.btnSearch.UseUnderline = true;
			this.btnSearch.Label = global::Mono.Unix.Catalog.GetString ("Search");
			this.table1.Add (this.btnSearch);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnSearch]));
			w1.LeftAttach = ((uint)(3));
			w1.RightAttach = ((uint)(4));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnShowYql = new global::Gtk.Button ();
			this.btnShowYql.CanFocus = true;
			this.btnShowYql.Name = "btnShowYql";
			this.btnShowYql.UseUnderline = true;
			this.btnShowYql.Label = global::Mono.Unix.Catalog.GetString ("_YQL...");
			this.table1.Add (this.btnShowYql);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnShowYql]));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ctlLikedByUserEntry = new global::Yamster.UserEntryWidget ();
			this.ctlLikedByUserEntry.Events = ((global::Gdk.EventMask)(256));
			this.ctlLikedByUserEntry.Name = "ctlLikedByUserEntry";
			this.table1.Add (this.ctlLikedByUserEntry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.ctlLikedByUserEntry]));
			w3.TopAttach = ((uint)(4));
			w3.BottomAttach = ((uint)(5));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ctlMentioningUserEntry = new global::Yamster.UserEntryWidget ();
			this.ctlMentioningUserEntry.Events = ((global::Gdk.EventMask)(256));
			this.ctlMentioningUserEntry.Name = "ctlMentioningUserEntry";
			this.table1.Add (this.ctlMentioningUserEntry);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.ctlMentioningUserEntry]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ctlSentByUserEntry = new global::Yamster.UserEntryWidget ();
			this.ctlSentByUserEntry.Events = ((global::Gdk.EventMask)(256));
			this.ctlSentByUserEntry.Name = "ctlSentByUserEntry";
			this.table1.Add (this.ctlSentByUserEntry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.ctlSentByUserEntry]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.chkWholeWords = new global::Gtk.CheckButton ();
			this.chkWholeWords.CanFocus = true;
			this.chkWholeWords.Name = "chkWholeWords";
			this.chkWholeWords.Label = global::Mono.Unix.Catalog.GetString ("Whole words only");
			this.chkWholeWords.DrawIndicator = true;
			this.chkWholeWords.UseUnderline = true;
			this.hbox4.Add (this.chkWholeWords);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.chkWholeWords]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 1;
			w6.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.rbMatchAll = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Match all terms"));
			this.rbMatchAll.CanFocus = true;
			this.rbMatchAll.Name = "rbMatchAll";
			this.rbMatchAll.DrawIndicator = true;
			this.rbMatchAll.UseUnderline = true;
			this.rbMatchAll.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox4.Add (this.rbMatchAll);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.rbMatchAll]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 2;
			w7.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.rbMatchAny = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Match any terms"));
			this.rbMatchAny.CanFocus = true;
			this.rbMatchAny.Name = "rbMatchAny";
			this.rbMatchAny.DrawIndicator = true;
			this.rbMatchAny.UseUnderline = true;
			this.rbMatchAny.Group = this.rbMatchAll.Group;
			this.hbox4.Add (this.rbMatchAny);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.rbMatchAny]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 3;
			w8.Expand = false;
			this.table1.Add (this.hbox4);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox4]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Sent By:");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Yam Contains:");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Mentioning:");
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w12.TopAttach = ((uint)(3));
			w12.BottomAttach = ((uint)(4));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Liked By:");
			this.table1.Add (this.label5);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
			w13.TopAttach = ((uint)(4));
			w13.BottomAttach = ((uint)(5));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtSearch = new global::Gtk.Entry ();
			this.txtSearch.CanFocus = true;
			this.txtSearch.Name = "txtSearch";
			this.txtSearch.IsEditable = true;
			this.txtSearch.InvisibleChar = '●';
			this.table1.Add (this.txtSearch);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtSearch]));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox2.Add (this.fixed1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.fixed1]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.ctlMessageViewer = new global::Yamster.MessageGrid ();
			this.ctlMessageViewer.Events = ((global::Gdk.EventMask)(256));
			this.ctlMessageViewer.Name = "ctlMessageViewer";
			this.vbox2.Add (this.ctlMessageViewer);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.ctlMessageViewer]));
			w17.Position = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("(SHIFT+click headers for multi-sort)");
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblSearchResults = new global::Gtk.Label ();
			this.lblSearchResults.Name = "lblSearchResults";
			this.lblSearchResults.Xalign = 1F;
			this.lblSearchResults.LabelProp = global::Mono.Unix.Catalog.GetString ("X messages matched.");
			this.hbox1.Add (this.lblSearchResults);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblSearchResults]));
			w19.PackType = ((global::Gtk.PackType)(1));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.lblSearchResults.Hide ();
			this.Hide ();
			this.txtSearch.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.txtSearch_KeyRelease);
			this.btnShowYql.Clicked += new global::System.EventHandler (this.btnShowYql_Clicked);
			this.btnSearch.Clicked += new global::System.EventHandler (this.btnSearch_Clicked);
			this.ctlMessageViewer.FocusedItemChanged += new global::System.EventHandler (this.ctlMessageViewer_FocusedItemChanged);
		}
	}
}
