
// This file has been generated by the GUI designer. Do not modify.
namespace Yamster
{
	public partial class GroupConfigScreen
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.CheckButton chkSyncInbox;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Yamster.GroupGrid ctlGroupGrid;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Button btnAddGroup;
		
		private global::Gtk.Button btnViewGroup;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Yamster.GroupConfigScreen
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Yamster.GroupConfigScreen";
			// Container child Yamster.GroupConfigScreen.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(6));
			// Container child vbox1.Gtk.Box+BoxChild
			this.chkSyncInbox = new global::Gtk.CheckButton ();
			this.chkSyncInbox.HeightRequest = 25;
			this.chkSyncInbox.CanFocus = true;
			this.chkSyncInbox.Name = "chkSyncInbox";
			this.chkSyncInbox.Label = global::Mono.Unix.Catalog.GetString ("Sync threads that appear in the Yammer Inbox");
			this.chkSyncInbox.Active = true;
			this.chkSyncInbox.DrawIndicator = true;
			this.chkSyncInbox.UseUnderline = true;
			this.chkSyncInbox.Xalign = 0F;
			this.vbox1.Add (this.chkSyncInbox);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.chkSyncInbox]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.Yalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Groups");
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ctlGroupGrid = new global::Yamster.GroupGrid ();
			this.ctlGroupGrid.Events = ((global::Gdk.EventMask)(256));
			this.ctlGroupGrid.Name = "ctlGroupGrid";
			this.hbox2.Add (this.ctlGroupGrid);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ctlGroupGrid]));
			w3.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnAddGroup = new global::Gtk.Button ();
			this.btnAddGroup.CanFocus = true;
			this.btnAddGroup.Name = "btnAddGroup";
			this.btnAddGroup.UseUnderline = true;
			this.btnAddGroup.Label = global::Mono.Unix.Catalog.GetString ("Add Another Group...");
			this.vbox2.Add (this.btnAddGroup);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnAddGroup]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnViewGroup = new global::Gtk.Button ();
			this.btnViewGroup.CanFocus = true;
			this.btnViewGroup.Name = "btnViewGroup";
			this.btnViewGroup.UseUnderline = true;
			this.btnViewGroup.Label = global::Mono.Unix.Catalog.GetString ("Web View...");
			this.vbox2.Add (this.btnViewGroup);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnViewGroup]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox2.Add (this.vbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w7.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.chkSyncInbox.Toggled += new global::System.EventHandler (this.chkSyncInbox_Toggled);
			this.ctlGroupGrid.FocusedItemChanged += new global::System.EventHandler (this.ctlGroupGrid_FocusedItemChanged);
			this.btnAddGroup.Clicked += new global::System.EventHandler (this.btnAddGroup_Clicked);
			this.btnViewGroup.Clicked += new global::System.EventHandler (this.btnViewGroup_Clicked);
		}
	}
}
