
// This file has been generated by the GUI designer. Do not modify.
namespace Yamster
{
	public partial class UserChooserWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Entry txtSearch;
		
		private global::Gtk.Button btnCancel;
		
		private global::Yamster.Grid ctlGrid;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Yamster.UserChooserWindow
			this.Name = "Yamster.UserChooserWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Select User");
			this.BorderWidth = ((uint)(4));
			this.Decorated = false;
			// Container child Yamster.UserChooserWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.txtSearch = new global::Gtk.Entry ();
			this.txtSearch.CanFocus = true;
			this.txtSearch.Name = "txtSearch";
			this.txtSearch.IsEditable = true;
			this.txtSearch.InvisibleChar = '●';
			this.hbox1.Add (this.txtSearch);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtSearch]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnCancel = new global::Gtk.Button ();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseUnderline = true;
			global::Gtk.Image w2 = new global::Gtk.Image ();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.btnCancel.Image = w2;
			this.hbox1.Add (this.btnCancel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnCancel]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.ctlGrid = new global::Yamster.Grid ();
			this.ctlGrid.Events = ((global::Gdk.EventMask)(256));
			this.ctlGrid.Name = "ctlGrid";
			this.vbox1.Add (this.ctlGrid);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.ctlGrid]));
			w5.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.txtSearch.Changed += new global::System.EventHandler (this.txtSearch_Changed);
			this.btnCancel.Clicked += new global::System.EventHandler (this.btnCancel_Clicked);
			this.ctlGrid.WidgetEvent += new global::Gtk.WidgetEventHandler (this.ctlGrid_Widget);
			this.ctlGrid.ViewUpdated += new global::System.EventHandler (this.ctlGrid_ViewUpdated);
		}
	}
}
