
// This file has been generated by the GUI designer. Do not modify.
namespace Yamster
{
	public partial class Grid
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView ctlTreeView;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Yamster.Grid
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Yamster.Grid";
			// Container child Yamster.Grid.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ctlTreeView = new global::Gtk.TreeView ();
			this.ctlTreeView.CanFocus = true;
			this.ctlTreeView.Name = "ctlTreeView";
			this.GtkScrolledWindow.Add (this.ctlTreeView);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.ctlTreeView.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.ctlTreeView_KeyPress);
			this.ctlTreeView.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.ctlTreeView_KeyRelease);
		}
	}
}
