
// This file has been generated by the GUI designer. Do not modify.
namespace Yamster
{
	public partial class SyncWindow
	{
		private global::Gtk.VBox dialog1_VBox;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Entry txtGroupHistory;
		
		private global::Gtk.Entry txtSyncGroup;
		
		private global::Gtk.Entry txtSyncStatus;
		
		private global::Gtk.Entry txtTotalMessages;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.RadioButton radAlgorithmOptimizeReading;
		
		private global::Gtk.RadioButton radAlgorithmBulkDownload;
		
		private global::Gtk.Label lblAlgorithm;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.CheckButton chkHistoryLimitDays;
		
		private global::Gtk.SpinButton txtHistoryLimitDays;
		
		private global::Gtk.Label lblHistoryLimitDays;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Label lblHistoryLimitDaysHint;
		
		private global::Gtk.HButtonBox hbuttonbox2;
		
		private global::Gtk.Button btnStart;
		
		private global::Gtk.Button btnStop;
		
		private global::Gtk.Button btnOnce;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Yamster.SyncWindow
			this.Name = "Yamster.SyncWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Yammer Sync");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Yamster.Resources.Yamster-16x16.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(15));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Yamster.SyncWindow.Gtk.Container+ContainerChild
			this.dialog1_VBox = new global::Gtk.VBox ();
			this.dialog1_VBox.Name = "dialog1_VBox";
			this.dialog1_VBox.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Status:");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Current Feed:");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("History Progress:");
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Yams In Database:");
			this.table1.Add (this.label5);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtGroupHistory = new global::Gtk.Entry ();
			this.txtGroupHistory.CanFocus = true;
			this.txtGroupHistory.Name = "txtGroupHistory";
			this.txtGroupHistory.IsEditable = false;
			this.txtGroupHistory.InvisibleChar = '?';
			this.table1.Add (this.txtGroupHistory);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtGroupHistory]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtSyncGroup = new global::Gtk.Entry ();
			this.txtSyncGroup.CanFocus = true;
			this.txtSyncGroup.Name = "txtSyncGroup";
			this.txtSyncGroup.IsEditable = false;
			this.txtSyncGroup.InvisibleChar = '?';
			this.table1.Add (this.txtSyncGroup);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtSyncGroup]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtSyncStatus = new global::Gtk.Entry ();
			this.txtSyncStatus.CanFocus = true;
			this.txtSyncStatus.Name = "txtSyncStatus";
			this.txtSyncStatus.IsEditable = false;
			this.txtSyncStatus.InvisibleChar = '?';
			this.table1.Add (this.txtSyncStatus);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtSyncStatus]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtTotalMessages = new global::Gtk.Entry ();
			this.txtTotalMessages.CanFocus = true;
			this.txtTotalMessages.Name = "txtTotalMessages";
			this.txtTotalMessages.IsEditable = false;
			this.txtTotalMessages.InvisibleChar = '?';
			this.table1.Add (this.txtTotalMessages);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtTotalMessages]));
			w8.TopAttach = ((uint)(3));
			w8.BottomAttach = ((uint)(4));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.BorderWidth = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.radAlgorithmOptimizeReading = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Optimize Reading: New content first, fill the history incrementally"));
			this.radAlgorithmOptimizeReading.CanFocus = true;
			this.radAlgorithmOptimizeReading.Name = "radAlgorithmOptimizeReading";
			this.radAlgorithmOptimizeReading.Active = true;
			this.radAlgorithmOptimizeReading.DrawIndicator = true;
			this.radAlgorithmOptimizeReading.UseUnderline = true;
			this.radAlgorithmOptimizeReading.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox4.Add (this.radAlgorithmOptimizeReading);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.radAlgorithmOptimizeReading]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.radAlgorithmBulkDownload = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Bulk Download: Fill the history first, then sync new content"));
			this.radAlgorithmBulkDownload.CanFocus = true;
			this.radAlgorithmBulkDownload.Name = "radAlgorithmBulkDownload";
			this.radAlgorithmBulkDownload.DrawIndicator = true;
			this.radAlgorithmBulkDownload.UseUnderline = true;
			this.radAlgorithmBulkDownload.Group = this.radAlgorithmOptimizeReading.Group;
			this.vbox4.Add (this.radAlgorithmBulkDownload);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.radAlgorithmBulkDownload]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.GtkAlignment.Add (this.vbox4);
			this.frame1.Add (this.GtkAlignment);
			this.lblAlgorithm = new global::Gtk.Label ();
			this.lblAlgorithm.Name = "lblAlgorithm";
			this.lblAlgorithm.LabelProp = global::Mono.Unix.Catalog.GetString ("Algorithm");
			this.lblAlgorithm.UseMarkup = true;
			this.frame1.LabelWidget = this.lblAlgorithm;
			this.hbox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame1]));
			w14.Position = 0;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.chkHistoryLimitDays = new global::Gtk.CheckButton ();
			this.chkHistoryLimitDays.CanFocus = true;
			this.chkHistoryLimitDays.Name = "chkHistoryLimitDays";
			this.chkHistoryLimitDays.Label = global::Mono.Unix.Catalog.GetString ("Skip threads older than");
			this.chkHistoryLimitDays.Active = true;
			this.chkHistoryLimitDays.DrawIndicator = true;
			this.chkHistoryLimitDays.UseUnderline = true;
			this.hbox2.Add (this.chkHistoryLimitDays);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.chkHistoryLimitDays]));
			w16.Position = 0;
			w16.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.txtHistoryLimitDays = new global::Gtk.SpinButton (1D, 999D, 1D);
			this.txtHistoryLimitDays.CanFocus = true;
			this.txtHistoryLimitDays.Name = "txtHistoryLimitDays";
			this.txtHistoryLimitDays.Adjustment.PageIncrement = 10D;
			this.txtHistoryLimitDays.ClimbRate = 1D;
			this.txtHistoryLimitDays.Numeric = true;
			this.txtHistoryLimitDays.Value = 90D;
			this.hbox2.Add (this.txtHistoryLimitDays);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtHistoryLimitDays]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblHistoryLimitDays = new global::Gtk.Label ();
			this.lblHistoryLimitDays.Name = "lblHistoryLimitDays";
			this.lblHistoryLimitDays.LabelProp = global::Mono.Unix.Catalog.GetString ("days");
			this.hbox2.Add (this.lblHistoryLimitDays);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblHistoryLimitDays]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.WidthRequest = 20;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox2.Add (this.fixed1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed1]));
			w19.Position = 3;
			w19.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblHistoryLimitDaysHint = new global::Gtk.Label ();
			this.lblHistoryLimitDaysHint.Name = "lblHistoryLimitDaysHint";
			this.lblHistoryLimitDaysHint.LabelProp = global::Mono.Unix.Catalog.GetString ("(i.e. XX/XX/XXXX)");
			this.hbox2.Add (this.lblHistoryLimitDaysHint);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblHistoryLimitDaysHint]));
			w20.Position = 4;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox5.Add (this.hbox2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox2]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox2.Add (this.vbox5);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox5]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			this.dialog1_VBox.Add (this.vbox2);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox [this.vbox2]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.BorderWidth = ((uint)(10));
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnStart = new global::Gtk.Button ();
			this.btnStart.CanFocus = true;
			this.btnStart.Name = "btnStart";
			this.btnStart.UseUnderline = true;
			this.btnStart.Label = global::Mono.Unix.Catalog.GetString ("Start");
			this.hbuttonbox2.Add (this.btnStart);
			global::Gtk.ButtonBox.ButtonBoxChild w24 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.btnStart]));
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnStop = new global::Gtk.Button ();
			this.btnStop.CanFocus = true;
			this.btnStop.Name = "btnStop";
			this.btnStop.UseUnderline = true;
			this.btnStop.Label = global::Mono.Unix.Catalog.GetString ("Stop");
			this.hbuttonbox2.Add (this.btnStop);
			global::Gtk.ButtonBox.ButtonBoxChild w25 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.btnStop]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnOnce = new global::Gtk.Button ();
			this.btnOnce.CanFocus = true;
			this.btnOnce.Name = "btnOnce";
			this.btnOnce.UseUnderline = true;
			this.btnOnce.Label = global::Mono.Unix.Catalog.GetString ("Once");
			this.hbuttonbox2.Add (this.btnOnce);
			global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.btnOnce]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			this.dialog1_VBox.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox [this.hbuttonbox2]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			this.Add (this.dialog1_VBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 518;
			this.DefaultHeight = 373;
			this.Hide ();
			this.chkHistoryLimitDays.Toggled += new global::System.EventHandler (this.chkHistoryLimitDays_Toggled);
			this.txtHistoryLimitDays.ValueChanged += new global::System.EventHandler (this.txtHistoryLimitDays_ValueChanged);
			this.btnStart.Clicked += new global::System.EventHandler (this.btnStart_Click);
			this.btnStop.Clicked += new global::System.EventHandler (this.btnStop_Click);
			this.btnOnce.Clicked += new global::System.EventHandler (this.btnOnce_Click);
		}
	}
}
