
// This file has been generated by the GUI designer. Do not modify.
namespace Yamster
{
	public partial class UserEntryWidget
	{
		private global::Gtk.Entry txtEntry;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Yamster.UserEntryWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Yamster.UserEntryWidget";
			// Container child Yamster.UserEntryWidget.Gtk.Container+ContainerChild
			this.txtEntry = new global::Gtk.Entry ();
			this.txtEntry.CanFocus = true;
			this.txtEntry.Name = "txtEntry";
			this.txtEntry.IsEditable = true;
			this.txtEntry.InvisibleChar = '●';
			this.Add (this.txtEntry);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.txtEntry.WidgetEvent += new global::Gtk.WidgetEventHandler (this.txtEntry_WidgetEvent);
			this.txtEntry.Changed += new global::System.EventHandler (this.txtEntry_Changed);
		}
	}
}
