
// This file has been generated by the GUI designer. Do not modify.
namespace Yamster
{
	public partial class ThreadViewer
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.VBox ctlVBox;
		
		private global::Yamster.ThreadViewerMessageTile messagetilewidget1;
		
		private global::Yamster.ThreadViewerMessageTile messagetilewidget2;
		
		private global::Yamster.ThreadViewerMessageTile messagetilewidget3;
		
		private global::Yamster.MessageComposer ctlMessageComposer;
		
		private global::Gtk.HBox ctlBottomHBox;
		
		private global::Gtk.Button btnOpenThread;
		
		private global::Gtk.Button btnRefreshThread;
		
		private global::Gtk.Button btnNewThread;
		
		private global::Gtk.CheckButton chkThreadRead;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Yamster.ThreadViewer
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 400;
			this.Name = "Yamster.ThreadViewer";
			// Container child Yamster.ThreadViewer.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.ctlVBox = new global::Gtk.VBox ();
			this.ctlVBox.Name = "ctlVBox";
			// Container child ctlVBox.Gtk.Box+BoxChild
			this.messagetilewidget1 = new global::Yamster.ThreadViewerMessageTile ();
			this.messagetilewidget1.Events = ((global::Gdk.EventMask)(256));
			this.messagetilewidget1.Name = "messagetilewidget1";
			this.messagetilewidget1.Highlighted = false;
			this.ctlVBox.Add (this.messagetilewidget1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.ctlVBox [this.messagetilewidget1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child ctlVBox.Gtk.Box+BoxChild
			this.messagetilewidget2 = new global::Yamster.ThreadViewerMessageTile ();
			this.messagetilewidget2.Events = ((global::Gdk.EventMask)(256));
			this.messagetilewidget2.Name = "messagetilewidget2";
			this.messagetilewidget2.Highlighted = false;
			this.ctlVBox.Add (this.messagetilewidget2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.ctlVBox [this.messagetilewidget2]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child ctlVBox.Gtk.Box+BoxChild
			this.messagetilewidget3 = new global::Yamster.ThreadViewerMessageTile ();
			this.messagetilewidget3.Events = ((global::Gdk.EventMask)(256));
			this.messagetilewidget3.Name = "messagetilewidget3";
			this.messagetilewidget3.Highlighted = false;
			this.ctlVBox.Add (this.messagetilewidget3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.ctlVBox [this.messagetilewidget3]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child ctlVBox.Gtk.Box+BoxChild
			this.ctlMessageComposer = new global::Yamster.MessageComposer ();
			this.ctlMessageComposer.HeightRequest = 170;
			this.ctlMessageComposer.Events = ((global::Gdk.EventMask)(256));
			this.ctlMessageComposer.Name = "ctlMessageComposer";
			this.ctlVBox.Add (this.ctlMessageComposer);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.ctlVBox [this.ctlMessageComposer]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			w1.Add (this.ctlVBox);
			this.GtkScrolledWindow.Add (w1);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w8.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.ctlBottomHBox = new global::Gtk.HBox ();
			this.ctlBottomHBox.Name = "ctlBottomHBox";
			this.ctlBottomHBox.Spacing = 6;
			// Container child ctlBottomHBox.Gtk.Box+BoxChild
			this.btnOpenThread = new global::Gtk.Button ();
			this.btnOpenThread.CanFocus = true;
			this.btnOpenThread.Name = "btnOpenThread";
			this.btnOpenThread.UseUnderline = true;
			this.btnOpenThread.Label = global::Mono.Unix.Catalog.GetString ("_Web View...");
			this.ctlBottomHBox.Add (this.btnOpenThread);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.ctlBottomHBox [this.btnOpenThread]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child ctlBottomHBox.Gtk.Box+BoxChild
			this.btnRefreshThread = new global::Gtk.Button ();
			this.btnRefreshThread.CanFocus = true;
			this.btnRefreshThread.Name = "btnRefreshThread";
			this.btnRefreshThread.UseUnderline = true;
			this.btnRefreshThread.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
			this.ctlBottomHBox.Add (this.btnRefreshThread);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.ctlBottomHBox [this.btnRefreshThread]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child ctlBottomHBox.Gtk.Box+BoxChild
			this.btnNewThread = new global::Gtk.Button ();
			this.btnNewThread.CanFocus = true;
			this.btnNewThread.Name = "btnNewThread";
			this.btnNewThread.UseUnderline = true;
			this.btnNewThread.Label = global::Mono.Unix.Catalog.GetString ("New Thread");
			this.ctlBottomHBox.Add (this.btnNewThread);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.ctlBottomHBox [this.btnNewThread]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child ctlBottomHBox.Gtk.Box+BoxChild
			this.chkThreadRead = new global::Gtk.CheckButton ();
			this.chkThreadRead.CanFocus = true;
			this.chkThreadRead.Name = "chkThreadRead";
			this.chkThreadRead.Label = global::Mono.Unix.Catalog.GetString ("_Read");
			this.chkThreadRead.DrawIndicator = true;
			this.chkThreadRead.UseUnderline = true;
			this.ctlBottomHBox.Add (this.chkThreadRead);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.ctlBottomHBox [this.chkThreadRead]));
			w12.PackType = ((global::Gtk.PackType)(1));
			w12.Position = 4;
			w12.Expand = false;
			this.vbox1.Add (this.ctlBottomHBox);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.ctlBottomHBox]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnOpenThread.Clicked += new global::System.EventHandler (this.btnOpenThread_Clicked);
			this.btnRefreshThread.Clicked += new global::System.EventHandler (this.btnRefreshThread_Clicked);
			this.btnNewThread.Clicked += new global::System.EventHandler (this.btnNewThread_Clicked);
			this.chkThreadRead.Toggled += new global::System.EventHandler (this.chkThreadRead_Toggled);
		}
	}
}
